### ISSUE TITLE
RepositoryCrawlerTest fails

### ISSUE THREAD

**Issue by caiusb** [caiusb/gitsvn#13]
The last assert in testProducesCorrectOutput is failing. I don't know if this is a regression, or it's OK for it to fail. I am submitting this as a bug a report so that the issue can be investigated at a later date.

I don't think that this affects our analysis in any way. I figure it's just some setup issue.

**Comment by cdmihai** [comment]
It is a stale test from the time the CSV aggregator hardcoded it's output file. The test is still good, it just needs to be updated.

The first assert is still valid, we could leave only that one.
