### ISSUE TITLE
We are only analysing the master branch

### ISSUE THREAD

**Issue by caiusb** [caiusb/gitsvn#27]
Having a look on how things work, I realised that we are only analysis the master branch.

The default `git clone` command only clones the master branch. So when we're running the analysis, it's run only on it. So our results are so far skewed a bit.

I'll fix it to work for all branches.

**Comment by altern** [comment]
Let's take a look at this tomorrow. It seems I have a workaround of how to
fix it.

**Comment by caiusb** [comment]
The fix is simple. I'll move your `branchesCheckout` method from `BranchCollector` to the beginning of the analysis and do it before we start the actual analysis. I'll push the changes in 30 mins or so.

**Comment by altern** [comment]
Yes. That's what I wanted to suggest :)

**Comment by caiusb** [comment]
Done
