### ISSUE TITLE
Merging infra with master

### ISSUE THREAD

**Issue by caiusb** [caiusb/gitsvn#8]
I think that the infrastructure is mature enough to warrant a merge into master. I don't think that things will change dramatically from now on. If they will, there we probably be forces we couldn't really have predicted.

So I am willing to do the merge, but I would like a second opinion. @cdmihai , what do you think?

**Comment by cdmihai** [comment]
Going to start reviewing it right away.

**Comment by cdmihai** [comment]
Looked through the code. 
I really like how the responsibilities are up split and made clear now. The pipeline is very easy to configure.

The AnalysisConfiguration in its current form is good for documenting and reproducing specific analyses. On the other hand when we want to run hundreds of analyses we need a different mechanism (the current one requires a new type for each project).

The pipeline should override all super interface methods and propagate the call to the filters, where appropriate (such as setRepository (done), reset and the rest). Who knows what the CommitFinder and other framework entities call upon them.

Everything looks good, let it merge :)
